// src/lib/begegnungen/crossings.ts — the crossings: what the practices are doing WITH each
// other, read out of the records that say so.
//
// WHY THIS EXISTS. /encounters used to lead with two large drawings of five completed
// encounters — the contact zone told retrospectively, while the living thing between the
// practices (a joint inquiry three of them are answering in parallel) had no page at all.
// Every other room now leads with its current protagonist. This module supplies The Middle's:
// the CROSSINGS, joint inquiries and encounters together, one ordered list, the open ones
// first.
//
// THE HOUSE RULE HOLDS THROUGHOUT: nothing here is written, summarised or rounded. Every
// string this module returns is a span of a committed file, carried with the path it came
// from and with the RULE that attached it, so a reader can check the attribution instead of
// trusting it. Where a record states nothing, this returns null and the page says so in
// words.
//
// PURE BY CONSTRUCTION. No import.meta.glob, no fs — callers hand over already-imported JSON,
// so this module is unit-testable against fixtures AND against the real committed exports.
//
// DEFENSIVE BY OBLIGATION. Its inputs are regenerated by an export chain that runs after
// every engine session; a shape that changes overnight must degrade to "the record states
// none", never to a build failure. Hence: every field is read through a guard, every array
// through `asArray`, and no function in this file throws.

// ————————————————————————————————————————————————— voices ———————————————————

/** The voices this ecology's records name. `unknown` is not a failure state — it is what an
 *  honest register says when tomorrow's export names a participant this site has never heard
 *  of, and it prints the raw id beside it rather than dropping the row. */
export type VoiceId =
  | 'ulysses'
  | 'meridian'
  | 'ensemble'
  | 'plenum'
  | 'datavism'
  | 'mrr'
  | 'conductor'
  | 'unknown'

/** Which recorded hue a voice wears. `neutral` is a DECLARATION, not an absence: the
 *  conductor lane is outside the categorical set of `ecology-voices` on purpose — "no
 *  resident — kept by the conductor", grayness is the meaning (src/lib/dataviz/palette.ts). */
export type VoiceHue = 'ulysses' | 'meridian' | 'ensemble' | 'plenum' | 'neutral'

export interface Voice {
  id: VoiceId
  /** how this site names the voice, in the hub's own wording */
  label: string
  /** the short form for a dense row */
  short: string
  hue: VoiceHue
  /** a standing caveat the site must print wherever this voice appears, or null */
  caveat: string | null
}

/**
 * MRR wears MERIDIAN'S hue and carries a caveat, and both halves of that are the current
 * wording canon rather than a design preference (docs/wording-kanon.md, Frank 2026-08-01):
 * the Meridian Research Runtime is the practice's TOOL, not a second practice and not the
 * practice's voice. Ownership settles the colour — one hue for one house. Authorship of the
 * individual run settles the caveat — what a run finds is a finding OF THE TOOL, and becomes
 * a statement of the collective only when the collective adopts it. The earlier framing
 * ("MRR = the architect's engineering line, never the collective") is dated and retired in
 * the canon; its core survives as exactly this caveat.
 */
export const VOICES: Record<VoiceId, Voice> = {
  ulysses: { id: 'ulysses', label: 'The Atelier · Ulysses', short: 'Ulysses', hue: 'ulysses', caveat: null },
  meridian: { id: 'meridian', label: 'The Field · Meridian', short: 'Meridian', hue: 'meridian', caveat: null },
  ensemble: { id: 'ensemble', label: 'The Studio · Ensemble', short: 'Ensemble', hue: 'ensemble', caveat: null },
  plenum: { id: 'plenum', label: 'The Plenum · data-snack.com', short: 'the Plenum', hue: 'plenum', caveat: null },
  datavism: {
    id: 'datavism',
    label: 'datavism.org',
    short: 'datavism',
    hue: 'neutral',
    caveat: 'a house of its own, outside this ecology’s four voices',
  },
  mrr: {
    id: 'mrr',
    label: 'MRR — the Meridian Research Runtime',
    short: 'MRR',
    hue: 'meridian',
    caveat:
      'Meridian’s tool, not Meridian’s voice: what a run finds is a finding of the tool, and becomes a statement of the collective only when the collective adopts it.',
  },
  conductor: {
    id: 'conductor',
    label: 'the conductor',
    short: 'the conductor',
    hue: 'neutral',
    caveat: null,
  },
  unknown: { id: 'unknown', label: 'a voice this site does not know', short: '—', hue: 'neutral', caveat: null },
}

/** Every spelling the committed records use for a voice, mapped to one id. The register, the
 *  ledger exports and the joint-inquiry fixture do not agree with each other — `frank` and
 *  `frank-bueltge` are the same hand, `data-snack-plenum` and `plenum` the same table — and
 *  the honest place to reconcile that is here, once, rather than in five templates. */
const VOICE_ALIASES: Record<string, VoiceId> = {
  ulysses: 'ulysses',
  atelier: 'ulysses',
  meridian: 'meridian',
  field: 'meridian',
  'field-research': 'meridian',
  ensemble: 'ensemble',
  studio: 'ensemble',
  plenum: 'plenum',
  'data-snack': 'plenum',
  'data-snack-plenum': 'plenum',
  datavism: 'datavism',
  'datavism-org': 'datavism',
  mrr: 'mrr',
  'meridian-runtime': 'mrr',
  frank: 'conductor',
  'frank-bueltge': 'conductor',
  conductor: 'conductor',
  'the-middle': 'conductor',
  'the-middle-editorial': 'conductor',
}

/** Never throws, never guesses: an id it does not know comes back as `unknown`, and callers
 *  print the raw string beside it. */
export function normaliseVoice(raw: unknown): VoiceId {
  if (typeof raw !== 'string') return 'unknown'
  return VOICE_ALIASES[raw.trim().toLowerCase()] ?? 'unknown'
}

export function voiceOf(raw: unknown): Voice {
  return VOICES[normaliseVoice(raw)]
}

// ————————————————————————————————————————————————— reading guards ———————————

const str = (v: unknown): string | null => {
  if (typeof v !== 'string') return null
  const t = v.trim()
  return t === '' ? null : t
}

const asArray = (v: unknown): unknown[] => (Array.isArray(v) ? v : [])

const obj = (v: unknown): Record<string, unknown> =>
  v !== null && typeof v === 'object' && !Array.isArray(v) ? (v as Record<string, unknown>) : {}

const ISO_DATE = /^\d{4}-\d{2}-\d{2}$/
const isoDate = (v: unknown): string | null => {
  const s = str(v)
  return s && ISO_DATE.test(s) ? s : null
}

// ————————————————————————————————————————————————— standing —————————————————

/** Where a crossing stands. `unstated` is a real third value and not a bug: two of the five
 *  recorded encounters carry `status: null`, and calling those "concluded" would close a
 *  crossing the register never closed. */
export type Standing = 'open' | 'concluded' | 'unstated'

const CONCLUDED = /\b(closed|concluded|resolved|complete[d]?|settled|withdrawn|abandoned|archived)\b/i
const OPEN = /\b(open|standing|running|active|unresolved|ongoing|review|waiting|pending)\b/i

/**
 * Derived from the record's own status words — and ONLY from its LEADING CLAUSE, which is where
 * the register states a standing. Its own format is `<standing> — <what has happened since>`,
 * and the second half runs to several hundred words on the newer encounters.
 *
 * That distinction is not fastidious, it is a bug this rule was written to fix. The first draft
 * scanned the whole string, and enc-2026-004 — whose status line opens `open/standing —` and then
 * reports, forty words later, that a source premiere "was KILLED/WITHDRAWN at source" — was filed
 * as CONCLUDED. The encounter is open; a thing INSIDE it was withdrawn. A page that closes a
 * crossing because of a word in its contents is reporting the opposite of the record.
 *
 * Where the leading clause carries no status word at all, the whole line is read rather than the
 * crossing being called unstated on a formatting technicality. Nothing is invented, and silence
 * is never read as a conclusion: no status is `unstated`, which is a third value on purpose.
 */
export function standingOf(statusText: string | null | undefined): Standing {
  const s = (statusText ?? '').trim()
  if (s === '') return 'unstated'
  const head = s.split(/[—–]/)[0].trim() || s
  const read = (t: string): Standing | null =>
    CONCLUDED.test(t) ? 'concluded' : OPEN.test(t) ? 'open' : null
  return read(head) ?? read(s) ?? 'unstated'
}

// ————————————————————————————————————————————————— quoted spans —————————————

export interface Quoted {
  /** the record's words, verbatim */
  text: string
  /** the path the words were read from — printed with the quote */
  source: string
  /** which field of the record it is, in the record's own vocabulary */
  label: string
}

const quoted = (text: string | null, source: string, label: string): Quoted | null =>
  text ? { text, source, label } : null

// ————————————————————————————————————————————————— attachment rules —————————

/**
 * WHICH RULE PUT A ROW ON A CROSSING. Every row prints its rule, so a visitor can see what
 * kind of evidence they are looking at instead of taking the arrangement on trust. The rules
 * are deliberately few and every one of them is EXPLICIT — a record naming the thing itself.
 * There is no "the prose mentions it" rule anywhere in this module; that was considered and
 * rejected for the same reason the studio's dossier rejected it (a house's own words about
 * the world are not a claim about another house).
 */
export type AttachmentRule =
  | 'ledger-event'
  | 'ledger-obligation'
  | 'ledger-non-participation'
  | 'register-status'
  | 'narrated-station'
  | 'ji-commitment'
  | 'ji-status'

/** Each label completes the sentence "attached by …", which is how the page prints it. */
export const CROSSING_RULE_LABELS: Record<AttachmentRule, string> = {
  'ledger-event': 'the encounter ledger’s own dated event',
  'ledger-obligation': 'an obligation the ledger records as still standing',
  'ledger-non-participation': 'the ledger’s own note of a documented non-relation',
  'register-status': 'the register’s own status line for this encounter',
  'narrated-station':
    'the contact zone’s own narrated station for this encounter — its editorial layer, named as such',
  'ji-commitment': 'the practice’s own Local Commitment to this inquiry',
  'ji-status': 'the practice’s own status note on its commitment',
}

export interface CrossingRow {
  /** the record's date, or null where it states none */
  date: string | null
  voice: VoiceId
  /** the raw participant id, printed where the voice is unknown to this site */
  rawVoice: string | null
  /** what the record calls this move, in its own vocabulary */
  label: string
  /** the record's words, verbatim */
  text: string
  /** an attribution the record itself carries for the quote, verbatim; null where it has none */
  attribution: string | null
  source: string
  by: AttachmentRule
}

// ————————————————————————————————————————————————— the crossing —————————————

export interface CrossingVoice {
  voice: VoiceId
  rawVoice: string
  /** the record's own word for what this voice is doing here (`source`, `receiver`,
   *  `conductor`, `ACTIVE`, `COMPLETED` …) — never a word written on this site */
  role: string | null
  /** the voice's own account of where it stands, verbatim, or null */
  localStatus: Quoted | null
  /** joint inquiries only: the question this voice posed under its own protocol, verbatim */
  localQuestion: Quoted | null
  /** joint inquiries only: the first claim of its answer, verbatim */
  headlineClaim: Quoted | null
  /** joint inquiries only: what it shipped, and where */
  output: { title: string; url: string } | null
}

export interface CrossingSource {
  path: string
  note: string
}

/** Two readings of one thing, both kept. Preserved dissent is an invariant of this ecology —
 *  the ledger records it as a first-class object precisely so no surface can quietly resolve
 *  it, and this dossier prints both sides side by side with the record's own closing line. */
export interface CrossingDivergence {
  leftLabel: string
  leftQuote: string
  leftVoice: VoiceId
  rightLabel: string
  rightQuote: string
  rightVoice: VoiceId
  closing: string | null
  source: string
}

export interface Crossing {
  kind: 'joint-inquiry' | 'encounter'
  id: string
  /** the deep-link anchor and dom id fragment: `crossing-<anchor>` */
  anchor: string
  /** every id another record might name this crossing by, lowercased — the register writes an
   *  encounter's full id, the practices' own records write the short one */
  matchIds: string[]
  title: string
  /** joint inquiries: the shared question the constellation was formed around, verbatim */
  question: Quoted | null
  standing: Standing
  /** the record's own status words, verbatim */
  status: Quoted | null
  asOf: string | null
  /** the newest date anywhere in the crossing's own record — the honest "is this alive" */
  lastMove: string | null
  recordUrl: string | null
  voices: CrossingVoice[]
  rows: CrossingRow[]
  sources: CrossingSource[]
  /** ledger exports only: what the record says did NOT happen, and why that is not a failure */
  nonParticipation: { voice: VoiceId; rawVoice: string; note: string; source: string }[]
  /** two readings the record refuses to resolve into one, where it records such a pair */
  divergence: CrossingDivergence | null
}

// ————————————————————————————————————————————————— joint inquiries ——————————

/** The shape `scripts/ecology/sync-joint-inquiries.mjs` writes. Everything optional, because
 *  the fixture it mirrors is the contact zone's and can grow a field any night. */
export interface JointInquiryInput {
  inquiry_id?: unknown
  slug?: unknown
  title?: unknown
  status?: unknown
  public_summary?: unknown
  initiated_by?: unknown
  coordination_profile?: unknown
  created_at?: unknown
  updated_at?: unknown
  record_url?: unknown
  source_commit?: unknown
  participants?: unknown
}

const JI_SOURCE = 'src/data/begegnungen/joint-inquiries.json'

export function buildJointInquiry(input: JointInquiryInput): Crossing | null {
  const raw = obj(input) as JointInquiryInput
  const id = str(raw.inquiry_id)
  if (!id) return null
  const title = str(raw.title) ?? id
  const statusWord = str(raw.status)
  const anchor = str(raw.slug) ?? id

  const voices: CrossingVoice[] = []
  const rows: CrossingRow[] = []

  for (const p of asArray(raw.participants)) {
    const rec = obj(p)
    const rawVoice = str(rec.practice_id) ?? ''
    const voice = normaliseVoice(rawVoice)
    const issuedAt = isoDate(rec.issued_at)
    const localQuestion = str(rec.local_question)
    const headlineClaim = str(rec.headline_claim)
    const statusNote = str(rec.local_status_note)
    const outputTitle = str(rec.output_title)
    const outputUrl = str(rec.output_url)
    // The practice's OWN record, where the fixture carries the pointer — printed instead of
    // the mirror's path, because that is where the words were written.
    const own = str(rec.source_uri) ?? JI_SOURCE

    voices.push({
      voice,
      rawVoice,
      role: str(rec.commitment_status) ?? str(rec.local_status),
      localStatus: quoted(statusNote, own, 'its own status note'),
      localQuestion: quoted(localQuestion, own, 'the question it posed under its own protocol'),
      headlineClaim: quoted(headlineClaim, own, 'the first claim of its answer'),
      output: outputTitle && outputUrl ? { title: outputTitle, url: outputUrl } : null,
    })

    if (localQuestion) {
      rows.push({
        date: issuedAt,
        voice,
        rawVoice: rawVoice || null,
        label: 'Local Commitment',
        text: localQuestion,
        attribution: str(rec.commitment_status),
        source: own,
        by: 'ji-commitment',
      })
    }
    if (statusNote) {
      rows.push({
        date: issuedAt,
        voice,
        rawVoice: rawVoice || null,
        label: str(rec.local_status) ?? 'status',
        text: statusNote,
        attribution: null,
        source: own,
        by: 'ji-status',
      })
    }
  }

  const dates = [isoDate(raw.created_at), isoDate(raw.updated_at), ...rows.map((r) => r.date)]
    .filter((d): d is string => d !== null)
    .sort()

  return {
    kind: 'joint-inquiry',
    id,
    anchor,
    matchIds: [id.toLowerCase()],
    title,
    question: quoted(str(raw.public_summary), JI_SOURCE, 'the shared question, as the contact zone constituted it'),
    standing: standingOf(statusWord),
    status: quoted(statusWord, JI_SOURCE, 'the inquiry’s own status'),
    asOf: isoDate(raw.updated_at),
    lastMove: dates.at(-1) ?? null,
    recordUrl: str(raw.record_url),
    voices,
    rows: sortRows(rows),
    sources: [
      { path: JI_SOURCE, note: 'the register of shared questions, mirrored from the contact zone’s own fixture' },
      ...[...new Set(voices.map((v) => v.localStatus?.source ?? v.localQuestion?.source).filter((s): s is string => !!s && s !== JI_SOURCE))].map(
        (path) => ({ path, note: 'the practice’s own record of its commitment' }),
      ),
    ],
    nonParticipation: [],
    divergence: null,
  }
}

// ————————————————————————————————————————————————— encounters ———————————————

/** One row of `src/data/begegnungen/register.json`. Every field optional on purpose: the
 *  register grew a structured `status` object in late July and older entries still carry
 *  `null`, so both shapes have to read without a branch in the template. */
export interface RegisterInput {
  encounter_id?: unknown
  title?: unknown
  status?: unknown
  approval?: unknown
  authored_by?: unknown
  participants?: unknown
  record_url?: unknown
  observed?: unknown
}

/** The ledger projection `src/data/begegnungen/<slug>/score.json` — present for the
 *  encounters the contact zone has exported, absent for the rest. */
export interface LedgerInput {
  encounter_id?: unknown
  headline?: unknown
  status?: unknown
  participants?: unknown
  non_participants?: unknown
  events?: unknown
  obligations?: unknown
  divergence?: unknown
}

/** The contact zone's narrated entrance for ONE encounter (`src/data/begegnungen/entrance.json`).
 *  It is an EDITORIAL layer over the same ledger — it gives each station a heading in the
 *  narrator's words and, occasionally, quotes a span the event payload does not isolate. It is
 *  read because those headings are the most readable labels the record carries, and it is
 *  labelled as editorial wherever it appears, never blended into the practices' own words. */
export interface NarrativeInput {
  encounter_id?: unknown
  authored_by?: unknown
  approval?: unknown
  stations?: unknown
}

const REGISTER_SOURCE = 'src/data/begegnungen/register.json'
const NARRATIVE_SOURCE = 'src/data/begegnungen/entrance.json'

/** `enc-2026-005-atlas-lent-not-lifted` → `enc-2026-005`. The same derivation
 *  research-ecology's export uses for the folder name (`shortEncounterSlug`). */
export function encounterSlug(encounterId: string): string {
  return encounterId.split('-').slice(0, 3).join('-')
}

/** The register's `status` in both shapes it has had: a bare string, and the object it became
 *  in late July. Neither is normalised into the other — the page prints what it finds. */
function readRegisterStatus(v: unknown): { statusLine: string | null; asOf: string | null } {
  const s = str(v)
  if (s) return { statusLine: s, asOf: null }
  const rec = obj(v)
  return { statusLine: str(rec.statusLine), asOf: isoDate(rec.as_of) }
}

export function buildEncounter(
  input: RegisterInput,
  ledgerInput?: LedgerInput,
  narrativeInput?: NarrativeInput,
): Crossing | null {
  const raw = obj(input) as RegisterInput
  const ledger = ledgerInput === undefined ? undefined : (obj(ledgerInput) as LedgerInput)
  const id = str(raw.encounter_id)
  if (!id) return null
  const slug = encounterSlug(id)
  const ledgerSource = `src/data/begegnungen/${slug}/score.json`
  const { statusLine, asOf } = readRegisterStatus(raw.status)

  // Voices: the register names them; where a ledger export exists it names them too, with the
  // practice's own account of what it did. The register is the spine (it covers every
  // encounter), the ledger fills in — never the other way round, so one uniform rule holds.
  const ledgerParticipants = new Map<string, Record<string, unknown>>()
  for (const p of asArray(ledger?.participants)) {
    const rec = obj(p)
    const key = str(rec.collective_id) ?? str(rec.actor_id)
    if (key) ledgerParticipants.set(key, rec)
  }

  const voices: CrossingVoice[] = []
  for (const p of asArray(raw.participants)) {
    const rec = obj(p)
    const rawVoice = str(rec.id) ?? ''
    if (!rawVoice) continue
    const fromLedger = ledgerParticipants.get(rawVoice)
    voices.push({
      voice: normaliseVoice(rawVoice),
      rawVoice,
      role: str(rec.role),
      localStatus: quoted(
        fromLedger ? str(fromLedger.local_status) : null,
        ledgerSource,
        'its own account of what it did here',
      ),
      localQuestion: null,
      headlineClaim: null,
      output: null,
    })
  }

  // The narrated stations, where the contact zone has written them for THIS encounter. Used
  // twice below: a station's heading becomes the label of the ledger event it narrates (the
  // narrator's words for what the move was, instead of the raw `offer.answered`), and a station
  // whose quote the event payload does not isolate becomes a row of its own, under its own rule.
  const stations = str(obj(narrativeInput).encounter_id) === id ? asArray(obj(narrativeInput).stations) : []
  const stationHeading = new Map<string, string>()
  for (const stRaw of stations) {
    const st = obj(stRaw)
    const evt = str(st.akte_event_id)
    const heading = str(st.heading)
    if (evt && heading && !stationHeading.has(evt)) stationHeading.set(evt, heading)
  }

  // The chronology: the ledger's own dated events, verbatim, each with the attribution the
  // ledger itself carries. An encounter without an export has none, and says so.
  const rows: CrossingRow[] = []
  const ledgerQuotes = new Set<string>()
  for (const e of asArray(ledger?.events)) {
    const rec = obj(e)
    const text = str(rec.quote)
    if (!text) continue // an event with no isolated quote is a row this site would have to write
    const issuer = obj(rec.issuer)
    const rawVoice = str(rec.lane) ?? str(issuer.collective_id) ?? str(issuer.actor_id) ?? ''
    ledgerQuotes.add(text)
    const eventId = str(rec.event_id)
    rows.push({
      date: isoDate(rec.date),
      voice: normaliseVoice(rawVoice),
      rawVoice: rawVoice || null,
      label: (eventId ? stationHeading.get(eventId) : null) ?? str(rec.event_type) ?? 'event',
      text,
      attribution: str(rec.attribution),
      source: ledgerSource,
      by: 'ledger-event',
    })
  }

  // A station the ledger's own event payload does not isolate a quote for. Not a duplicate and
  // not a gap-filler: it is a span of the record the events skip, and it says whose layer it is.
  for (const stRaw of stations) {
    const st = obj(stRaw)
    const text = str(st.quote)
    if (!text || ledgerQuotes.has(text)) continue
    rows.push({
      date: null,
      voice: 'conductor',
      rawVoice: str(obj(narrativeInput).authored_by),
      label: str(st.heading) ?? 'station',
      text,
      attribution: str(st.attribution),
      source: NARRATIVE_SOURCE,
      by: 'narrated-station',
    })
  }

  for (const o of asArray(ledger?.obligations)) {
    const rec = obj(o)
    const text = str(rec.clause_text)
    if (!text) continue
    const rawVoice = str(rec.lane) ?? ''
    rows.push({
      date: null,
      voice: normaliseVoice(rawVoice),
      rawVoice: rawVoice || null,
      label: str(rec.label) ?? 'obligation',
      text,
      attribution: str(rec.status) ? `obligation ${str(rec.status)}` : null,
      source: ledgerSource,
      by: 'ledger-obligation',
    })
  }

  // The register's own status line is itself a dated statement about the crossing, and for
  // three of the five encounters it is the ONLY prose the record carries. It goes in as a row
  // under its own rule rather than being quietly promoted into the chronology.
  if (statusLine) {
    rows.push({
      date: asOf,
      voice: 'conductor',
      rawVoice: str(raw.authored_by),
      label: 'the register’s standing',
      text: statusLine,
      attribution: str(raw.approval) ? `wording ${str(raw.approval)}` : null,
      source: REGISTER_SOURCE,
      by: 'register-status',
    })
  }

  const nonParticipation = asArray(ledger?.non_participants).flatMap((n) => {
    const rec = obj(n)
    const rawVoice = str(rec.collective_id) ?? ''
    const note = str(rec.note)
    return note ? [{ voice: normaliseVoice(rawVoice), rawVoice, note, source: ledgerSource }] : []
  })

  // Preserved dissent, where the ledger records it. Both sides or neither: a divergence with
  // one half quoted would be the resolution the record refused to make.
  const dv = obj(ledger?.divergence)
  const leftQuote = str(dv.leftQuote)
  const rightQuote = str(dv.rightQuote)
  const divergence: CrossingDivergence | null =
    leftQuote && rightQuote
      ? {
          leftLabel: str(dv.leftLabel) ?? 'one reading',
          leftQuote,
          leftVoice: normaliseVoice(dv.leftLane),
          rightLabel: str(dv.rightLabel) ?? 'the other reading',
          rightQuote,
          rightVoice: normaliseVoice(dv.rightLane),
          closing: str(dv.closing),
          source: ledgerSource,
        }
      : null

  const ledgerStatus = readRegisterStatus(ledger?.status)
  const dates = [asOf, ledgerStatus.asOf, ...rows.map((r) => r.date)]
    .filter((d): d is string => d !== null)
    .sort()

  const sources: CrossingSource[] = [
    { path: REGISTER_SOURCE, note: 'the register of recorded encounters, exported by the contact zone' },
  ]
  if (ledger) {
    sources.push({ path: ledgerSource, note: 'this encounter’s own ledger projection — every event, dated, as it was filed' })
  }
  if (stations.length > 0) {
    sources.push({ path: NARRATIVE_SOURCE, note: 'the contact zone’s narrated stations for this encounter — its editorial layer over the same ledger' })
  }

  return {
    kind: 'encounter',
    id,
    anchor: slug,
    matchIds: [...new Set([id.toLowerCase(), slug.toLowerCase()])],
    title: str(raw.title) ?? str(ledger?.headline) ?? id,
    question: null,
    standing: standingOf(statusLine),
    status: quoted(statusLine, REGISTER_SOURCE, 'the register’s own status line'),
    asOf: asOf ?? ledgerStatus.asOf,
    lastMove: dates.at(-1) ?? null,
    recordUrl: str(raw.record_url),
    voices,
    rows: sortRows(rows),
    sources,
    nonParticipation,
    divergence,
  }
}

// ————————————————————————————————————————————————— ordering —————————————————

/** Newest first, and a row the record left undated sorts last rather than to 1970 — an
 *  obligation states no date because it is still standing, not because it is old. */
export function sortRows(rows: readonly CrossingRow[]): CrossingRow[] {
  return [...rows].sort((a, b) => {
    if (a.date && b.date && a.date !== b.date) return b.date.localeCompare(a.date)
    if (a.date && !b.date) return -1
    if (!a.date && b.date) return 1
    return 0
  })
}

const STANDING_ORDER: Record<Standing, number> = { open: 0, unstated: 1, concluded: 2 }

/**
 * The order the page reads in: what is still open leads, and inside each group the crossing
 * that moved most recently leads. Joint inquiries sort ahead of encounters at equal standing
 * and equal date — the shared question is the thing the practices are doing together NOW,
 * and an encounter of the same day is its context.
 */
export function sortCrossings(crossings: readonly Crossing[]): Crossing[] {
  return [...crossings].sort(
    (a, b) =>
      STANDING_ORDER[a.standing] - STANDING_ORDER[b.standing] ||
      (b.lastMove ?? '').localeCompare(a.lastMove ?? '') ||
      (a.kind === b.kind ? 0 : a.kind === 'joint-inquiry' ? -1 : 1) ||
      a.id.localeCompare(b.id),
  )
}

export interface CrossingsInput {
  inquiries: readonly JointInquiryInput[]
  register: readonly RegisterInput[]
  /** ledger projections keyed by their short slug (`enc-2026-005`) — the two the contact zone
   *  has exported today, more when it exports more */
  ledgers: Readonly<Record<string, LedgerInput>>
  /** the narrated entrance, which the export writes for exactly one encounter at a time */
  narrative?: NarrativeInput
}

export function buildCrossings(input: CrossingsInput): Crossing[] {
  const jis = asArray(input.inquiries)
    .map((ji) => buildJointInquiry(obj(ji)))
    .filter((c): c is Crossing => c !== null)
  const encounters = asArray(input.register)
    .map((e) => {
      const rec = obj(e) as RegisterInput
      const id = str(rec.encounter_id)
      const ledger = id ? (obj(input.ledgers)[encounterSlug(id)] as LedgerInput | undefined) : undefined
      return buildEncounter(rec, ledger, input.narrative)
    })
    .filter((c): c is Crossing => c !== null)
  return sortCrossings([...jis, ...encounters])
}

/** The page's protagonist: the open crossing that moved most recently — a joint inquiry where
 *  one is open, because `sortCrossings` puts it there. Where nothing is open, the newest
 *  crossing of any standing leads, which is still the honest answer to "what is happening". */
export function leadCrossing(crossings: readonly Crossing[]): Crossing | undefined {
  return crossings[0]
}

/** Every voice that appears in any crossing, in the order the recorded quartet is written.
 *  Used for the page's legend — a colour is only ever explained where it is used. */
export function crossingVoices(crossings: readonly Crossing[]): Voice[] {
  const order: VoiceId[] = ['ulysses', 'meridian', 'ensemble', 'plenum', 'mrr', 'datavism', 'conductor', 'unknown']
  const seen = new Set<VoiceId>()
  for (const c of crossings) {
    for (const v of c.voices) seen.add(v.voice)
    for (const r of c.rows) seen.add(r.voice)
  }
  return order.filter((id) => seen.has(id)).map((id) => VOICES[id])
}
